--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BlockHorizons/BlockSniper
submodule: true
projects:
  BlockSniper:
    path: ""
    icon: resources/block_sniper_logo.png
    compressBuilds: false
    fullGzip: 9
...
