{
  "name": "BlockSniper",
  "version": "4.0.0",
  "description": "A brush world editing plugin for PocketMine-MP",
  "api": [
    "4.0.0"
  ],
  "author": "BlockHorizons",
  "authors": [
    "Sandertv (`@Sandertv`)",
    "Chris-Prime (`@PrimusLV`)"
  ],
  "main": "BlockHorizons\\BlockSniper\\Loader",
  "softdepend": [
    "MyPlot"
  ],
  "permissions": {
    "blocksniper.myplot.bypass": {
      "default": false,
      "description": "Allows bypassing MyPlot plot protection."
    },
    "blocksniper.myplot.allow-outside": {
      "default": "op",
      "description": "Allows using BlockSniper outside of plot worlds limitlessly."
    },
    "blocksniper.command.brush": {
      "default": "op",
      "description": "Allows access to the brush wand command."
    },
    "blocksniper.command.undo": {
      "default": "op",
      "description": "Allows access to the undo command."
    },
    "blocksniper.command.redo": {
      "default": "op",
      "description": "Allows access to the redo command."
    },
    "blocksniper.command.blocksniper": {
      "default": "op",
      "description": "Allows access to the BlockSniper command."
    },
    "blocksniper.command.clone": {
      "default": "op",
      "description": "Allows access to the clone command."
    },
    "blocksniper.command.paste": {
      "default": "op",
      "description": "Allows access to the paste command."
    },
    "blocksniper.command.deselect": {
      "default": "op",
      "description": "Allows access to the deselect command."
    },
    "blocksniper.clone.copy": {
      "default": "op",
      "description": "Allows access to the copy clone type."
    },
    "blocksniper.clone.schematic": {
      "default": "op",
      "description": "Allows access to the schematic clone type."
    },
    "blocksniper.paste.copy": {
      "default": "op",
      "description": "Allows access to the copy paste type."
    },
    "blocksniper.paste.schematic": {
      "default": "op",
      "description": "Allows access to the schematic paste type."
    }
  }
}
