---
name: "BlockSniper"
version: 0.1.0
api: [2.0.0, 2.1.0, 3.0.0-ALPHA1 3.0.0-ALPHA2]
author: "Sandertv"
main: Sandertv\BlockSniper\Loader

permissions:
    blocksniper:
        default: false
        description: "Allows access to all BlockSniper features."
        children:
            blocksniper.command:
                default: false
                description: "Allows access to all BlockSniper command features."
                children:
                    blocksniper.command.snipe:
                        default: op
                        description: "Allows access to the snipe command."
                    blocksniper.command.brushwand:
                        default: op
                        description: "Allows access to the brush wand command."
                    blocksniper.command.undo:
                        default: op
                        description: "Allows access to the undo command."
            blocksniper.type:
                default: false
                description: "Allows access to all BlockSniper types."
                children:
                    blocksniper.type.overlay:
                        default: op
                        description: "Allows access to the overlay type."
                    blocksniper.type.layer:
                        default: op
                        description: "Allows access to the layer type"
                    blocksniper.type.replace:
                        default: op
                        description: "Allows access to the replace type"
                    blocksniper.type.clean:
                        default: op
                        description: "Allows access to the clean type"
                    blocksniper.type.drain:
                        default: op
                        description: "Allows access to the drain type"
                    blocksniper.type.leafblower:
                        default: op
                        description: "Allows access to the leaf blower type"
                    blocksniper.type.flatten:
                        default: op
                        description: "Allows access to the flatten type"
            blocksniper.shape:
                default: false
                description: "Allows access to all BlockSniper shapes."
                children:
                    blocksniper.shape.sphere:
                        default: op
                        description: "Allows access to the sphere shape."
                    blocksniper.shape.cuboid:
                        default: op
                        description: "Allows access to the cuboid shape."
                    blocksniper.shape.standingcylinder:
                        default: op
                        description: "Allows access to the standing cylinder shape."
                    blocksniper.shape.cube:
                        default: op
                        description: "Allows access to the cube shape."
...
